"""Central constants for BDR hook generation and writeback."""

from __future__ import annotations

from bdr_agent.stages.company_research.config import (
    BIGQUERY_DATASET,
    GCP_PROJECT_ID,
    GCS_ARTIFACT_URI_PREFIX,
    HOOKS_TABLE,
    OUTPUTS_TABLE,
    RUNS_TABLE,
    bigquery_table_id,
)

SCHEMA_VERSION = "bdr_agent_hook.v1"
STAGE = "outreach_writeback"

HOOK_PROPERTY_NAME = "ai_hook_intro"
SOURCES_PROPERTY_NAME = "ai_hook_sources"
CREATED_AT_PROPERTY_NAME = "ai_personalized_at"

HUBSPOT_BASE_URL = "https://api.hubapi.com"
HUBSPOT_CONTACT_OBJECT_TYPE = "contacts"
HUBSPOT_LEAD_OBJECT_TYPE = "0-136"
HUBSPOT_TOKEN_ENV_CANDIDATES = (
    "BDR_AGENT_HUBSPOT_API_KEY",
    "HUBSPOT_API_KEY",
    "HUBSPOT_PRIVATE_APP_TOKEN",
    "GENERAL_HUBSPOT_APP_TOKEN",
    "HUBSPOT_ACCESS_TOKEN",
)

HOOK_STATUS_GENERATED = "generated"
HOOK_STATUS_GENERATED_DRY_RUN = "generated_dry_run"
HOOK_STATUS_CANDIDATE_GENERATED = "candidate_generated"
HOOK_STATUS_QUALITY_PASSED = "quality_passed"
HOOK_STATUS_QUALITY_FAILED = "quality_failed"
HOOK_STATUS_REWRITE_REQUESTED = "rewrite_requested"
HOOK_STATUS_REWRITTEN_QUALITY_PASSED = "rewritten_quality_passed"
HOOK_STATUS_WRITEBACK_SUCCEEDED = "writeback_succeeded"
HOOK_STATUS_WRITEBACK_FAILED = "writeback_failed"
HOOK_STATUS_WRITEBACK_PARTIAL = "writeback_partial"
GENERATION_STATUS_CANDIDATE_GENERATED = "candidate_generated"
GENERATION_STATUS_QUALITY_PASSED = "quality_passed"
GENERATION_STATUS_QUALITY_FAILED = "quality_failed"
GENERATION_STATUS_REWRITE_REQUESTED = "rewrite_requested"
GENERATION_STATUS_REWRITTEN_QUALITY_PASSED = "rewritten_quality_passed"
GENERATION_STATUS_WRITEBACK_SUCCEEDED = "writeback_succeeded"
GENERATION_STATUS_WRITEBACK_FAILED = "writeback_failed"
VALID_GENERATION_STATUSES = {
    GENERATION_STATUS_CANDIDATE_GENERATED,
    GENERATION_STATUS_QUALITY_PASSED,
    GENERATION_STATUS_QUALITY_FAILED,
    GENERATION_STATUS_REWRITE_REQUESTED,
    GENERATION_STATUS_REWRITTEN_QUALITY_PASSED,
    GENERATION_STATUS_WRITEBACK_SUCCEEDED,
    GENERATION_STATUS_WRITEBACK_FAILED,
}
GENERATION_STATUS_TRANSITIONS = {
    GENERATION_STATUS_CANDIDATE_GENERATED: {
        GENERATION_STATUS_QUALITY_PASSED,
        GENERATION_STATUS_QUALITY_FAILED,
        GENERATION_STATUS_REWRITE_REQUESTED,
    },
    GENERATION_STATUS_REWRITE_REQUESTED: {
        GENERATION_STATUS_REWRITTEN_QUALITY_PASSED,
        GENERATION_STATUS_QUALITY_FAILED,
    },
    GENERATION_STATUS_QUALITY_FAILED: set(),
    GENERATION_STATUS_QUALITY_PASSED: {
        GENERATION_STATUS_WRITEBACK_SUCCEEDED,
        GENERATION_STATUS_WRITEBACK_FAILED,
    },
    GENERATION_STATUS_REWRITTEN_QUALITY_PASSED: {
        GENERATION_STATUS_WRITEBACK_SUCCEEDED,
        GENERATION_STATUS_WRITEBACK_FAILED,
    },
    GENERATION_STATUS_WRITEBACK_SUCCEEDED: set(),
    GENERATION_STATUS_WRITEBACK_FAILED: set(),
}

WRITEBACK_STATUS_SKIPPED_DRY_RUN = "skipped_dry_run"
WRITEBACK_STATUS_SUCCEEDED = "succeeded"
WRITEBACK_STATUS_FAILED = "failed"
WRITEBACK_STATUS_NOT_ATTEMPTED = "not_attempted"
WRITER_MODE_CANDIDATE_GENERATION = "candidate_generation"
WRITER_MODE_REWRITE = "rewrite"
WRITER_MODE_TEMPLATE = "template"
VALID_WRITER_MODES = {
    WRITER_MODE_CANDIDATE_GENERATION,
    WRITER_MODE_REWRITE,
    WRITER_MODE_TEMPLATE,
}

DEFAULT_STYLE_PROFILE_ID = "generic_bdr"
DEFAULT_STYLE_PROFILE_VERSION = "style_profiles_v1"
DEFAULT_STYLE_PROFILE_FALLBACK_REASON = "hubspot_owner_id_missing"
DEFAULT_POSITIONING_SNAPSHOT_VERSION = "positioning_guide_v1"

HOOK_ANGLE_PRODUCT_TRACTION = "product_traction"
HOOK_ANGLE_COMPANY_RESEARCH = "company_research"
HOOK_ANGLE_PERSON_RESEARCH = "person_research"
HOOK_ANGLE_DEFAULT = "default_angle"

GCS_ARTIFACT_PREFIX = GCS_ARTIFACT_URI_PREFIX

